### Step 1: Import Libraries and Load Data

In [13]:
import pandas as pd
import numpy as np

# Sample messy dataset
data = {
    "CustomerID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "CustomerName": ["Raj", None, "Simran", "Amit", "Priya", "Karan", "Neha", None, "Vikas", "Asha"],
    "Age": [25, None, 30, "unknown", 45, 29, None, 33, "N/A", 40],
    "Price": [500, 1500, None, 2000, 1200, "NA", 800, 1000, None, 2200],
    "Quantity": [2, None, 3, "two", 5, 1, None, "3", 4, 2],
    "Discount": [5, 10, None, "N/A", 15, 0, 5, None, 10, "none"],
    "ReceivedDate": ["2025-08-01", "2025/08/03", None, "03-08-2025", "2025-08-05", "Invalid", "2025-08-07", None, "2025-08-09", "2025-08-10"],
    "DeliveryDate": ["2025-08-05", None, "2025-08-06", "06-08-2025", "2025/08/09", None, "2025-08-12", "Invalid", "2025-08-13", "2025-08-14"],
    "Email": ["raj@example.com", None, "simran@example", "amit@", "priya@example.com", "karan#mail.com", None, "neha@example.com", "vikas@", "asha@example.com"],
    "Review": ["Good", "Bad", None, "Average", "Excellent", "Poor", "Bad", None, "Good", "Excellent"]
}

# Load into DataFrame
df = pd.DataFrame(data)

# Display initial dataset
df

,CustomerID,CustomerName,Age,Price,Quantity,Discount,ReceivedDate,DeliveryDate,Email,Review
0,101,Raj,25,500,2,5,2025-08-01,2025-08-05,raj@example.com,Good
1,102,None,None,1500,None,10,2025/08/03,None,None,Bad
2,103,Simran,30,None,3,None,None,2025-08-06,simran@example,None
3,104,Amit,unknown,2000,two,N/A,03-08-2025,06-08-2025,amit@,Average
4,105,Priya,45,1200,5,15,2025-08-05,2025/08/09,priya@example.com,Excellent
5,106,Karan,29,NA,1,0,Invalid,None,karan#mail.com,Poor
6,107,Neha,None,800,None,5,2025-08-07,2025-08-12,None,Bad
7,108,None,33,1000,3,None,None,Invalid,neha@example.com,None
8,109,Vikas,N/A,None,4,10,2025-08-09,2025-08-13,vikas@,Good
9,110,Asha,40,2200,2,none,2025-08-10,2025-08-14,asha@example.com,Excellent

### Step 2: Check Missing Values

In [14]:
# Check missing values in each column
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 CustomerID      0
CustomerName    2
Age             2
Price           2
Quantity        2
Discount        2
ReceivedDate    2
DeliveryDate    2
Email           2
Review          2
dtype: int64

In [15]:
# Summary statistics for numeric columns
df.describe()

       CustomerID
count    10.00000
mean    105.50000
std       3.02765
min     101.00000
25%     103.25000
50%     105.50000
75%     107.75000
max     110.00000

### Step 3: Handle Missing & Invalid Values

In [18]:
# Age column
df["Age"] = df["Age"].replace(["unknown", "N/A"], np.nan)
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Price column
df["Price"] = df["Price"].replace(["NA", "N/A"], np.nan)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df["Price"] = df["Price"].fillna(df["Price"].mean())

# Quantity column
df["Quantity"] = df["Quantity"].replace(["two"], 2)
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

# Discount column
df["Discount"] = df["Discount"].replace(["N/A", "none"], np.nan)
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce")
df["Discount"] = df["Discount"].fillna(0)
print(df)

   CustomerID CustomerName        Age        Price  Quantity  Discount  \
0         101          Raj  25.000000   500.000000       2.0       5.0
1         102         None  33.666667  1500.000000       2.5      10.0
2         103       Simran  30.000000  1314.285714       3.0       0.0
3         104         Amit  33.666667  2000.000000       2.0       0.0
4         105        Priya  45.000000  1200.000000       5.0      15.0
5         106        Karan  29.000000  1314.285714       1.0       0.0
6         107         Neha  33.666667   800.000000       2.5       5.0
7         108         None  33.000000  1000.000000       3.0       0.0
8         109        Vikas  33.666667  1314.285714       4.0      10.0
9         110         Asha  40.000000  2200.000000       2.0       0.0

  ReceivedDate DeliveryDate              Email     Review
0   2025-08-01   2025-08-05    raj@example.com       Good
1   2025/08/03         None               None        Bad
2         None   2025-08-06     simran@example       None
3   03-08-2025   06-08-2025              amit@    Average
4   2025-08-05   2025/08/09  priya@example.com  Excellent
5      Invalid         None     karan#mail.com       Poor
6   2025-08-07   2025-08-12               None        Bad
7         None      Invalid   neha@example.com       None
8   2025-08-09   2025-08-13             vikas@       Good
9   2025-08-10   2025-08-14   asha@example.com  Excellent

### Step 4: Clean & Standardize Dates

In [19]:
# Convert date columns to datetime, invalid parsing becomes NaT
df["ReceivedDate"] = pd.to_datetime(df["ReceivedDate"], errors="coerce")
df["DeliveryDate"] = pd.to_datetime(df["DeliveryDate"], errors="coerce")

# Fill missing/invalid dates with a reference date
df["ReceivedDate"] = df["ReceivedDate"].fillna(pd.Timestamp("2025-08-01"))
df["DeliveryDate"] = df["DeliveryDate"].fillna(pd.Timestamp("2025-08-05"))

# Display dataset after cleaning dates
df[["ReceivedDate", "DeliveryDate"]]

  ReceivedDate DeliveryDate
0   2025-08-01   2025-08-05
1   2025-08-01   2025-08-05
2   2025-08-01   2025-08-06
3   2025-08-01   2025-08-05
4   2025-08-05   2025-08-05
5   2025-08-01   2025-08-05
6   2025-08-07   2025-08-12
7   2025-08-01   2025-08-05
8   2025-08-09   2025-08-13
9   2025-08-10   2025-08-14

### Step 5: Clean & Standardize Text Columns

In [20]:
# CustomerName: fill missing, capitalize
df["CustomerName"] = df["CustomerName"].fillna("Unknown")
df["CustomerName"] = df["CustomerName"].str.title().str.strip()

# Email: fill missing, lowercase, remove spaces
df["Email"] = df["Email"].fillna("Not Provided")
df["Email"] = df["Email"].str.lower().str.strip()

# Review: fill missing, standardize text
df["Review"] = df["Review"].fillna("No Review")
df["Review"] = df["Review"].str.title().str.strip()

# Display cleaned text columns
df[["CustomerName", "Email", "Review"]]

  CustomerName              Email     Review
0          Raj    raj@example.com       Good
1      Unknown       not provided        Bad
2       Simran     simran@example  No Review
3         Amit              amit@    Average
4        Priya  priya@example.com  Excellent
5        Karan     karan#mail.com       Poor
6         Neha       not provided        Bad
7      Unknown   neha@example.com  No Review
8        Vikas             vikas@       Good
9         Asha   asha@example.com  Excellent

### Step 6a: TotalPrice

In [21]:
df["TotalPrice"] = df["Price"] * df["Quantity"] - df["Discount"]
df[["Price", "Quantity", "Discount", "TotalPrice"]]

         Price  Quantity  Discount   TotalPrice
0   500.000000       2.0       5.0   995.000000
1  1500.000000       2.5      10.0  3740.000000
2  1314.285714       3.0       0.0  3942.857143
3  2000.000000       2.0       0.0  4000.000000
4  1200.000000       5.0      15.0  5985.000000
5  1314.285714       1.0       0.0  1314.285714
6   800.000000       2.5       5.0  1995.000000
7  1000.000000       3.0       0.0  3000.000000
8  1314.285714       4.0      10.0  5247.142857
9  2200.000000       2.0       0.0  4400.000000

### Step 6b: DeliveryTime

In [22]:
df["DeliveryTime"] = (df["DeliveryDate"] - df["ReceivedDate"]).dt.days
df[["ReceivedDate", "DeliveryDate", "DeliveryTime"]]

  ReceivedDate DeliveryDate  DeliveryTime
0   2025-08-01   2025-08-05             4
1   2025-08-01   2025-08-05             4
2   2025-08-01   2025-08-06             5
3   2025-08-01   2025-08-05             4
4   2025-08-05   2025-08-05             0
5   2025-08-01   2025-08-05             4
6   2025-08-07   2025-08-12             5
7   2025-08-01   2025-08-05             4
8   2025-08-09   2025-08-13             4
9   2025-08-10   2025-08-14             4

### Step 6c: Review Score

In [23]:
review_map = {
    "No Review": 0,
    "Poor": 1,
    "Bad": 2,
    "Average": 3,
    "Good": 4,
    "Excellent": 5
}

df["ReviewScore"] = df["Review"].map(review_map)
df[["Review", "ReviewScore"]]

      Review  ReviewScore
0       Good            4
1        Bad            2
2  No Review            0
3    Average            3
4  Excellent            5
5       Poor            1
6        Bad            2
7  No Review            0
8       Good            4
9  Excellent            5

### Step 7: Export Cleaned Dataset

In [25]:
# Export final cleaned dataset
df.to_csv("Cleaned_Customer_Data.csv", index=False)
df.to_excel("Cleaned_Customer_Data.xlsx", index=False)
print(df)

   CustomerID CustomerName        Age        Price  Quantity  Discount  \
0         101          Raj  25.000000   500.000000       2.0       5.0
1         102      Unknown  33.666667  1500.000000       2.5      10.0
2         103       Simran  30.000000  1314.285714       3.0       0.0
3         104         Amit  33.666667  2000.000000       2.0       0.0
4         105        Priya  45.000000  1200.000000       5.0      15.0
5         106        Karan  29.000000  1314.285714       1.0       0.0
6         107         Neha  33.666667   800.000000       2.5       5.0
7         108      Unknown  33.000000  1000.000000       3.0       0.0
8         109        Vikas  33.666667  1314.285714       4.0      10.0
9         110         Asha  40.000000  2200.000000       2.0       0.0

  ReceivedDate DeliveryDate              Email     Review   TotalPrice  \
0   2025-08-01   2025-08-05    raj@example.com       Good   995.000000
1   2025-08-01   2025-08-05       not provided        Bad  3740.000000
2   2025-08-01   2025-08-06     simran@example  No Review  3942.857143
3   2025-08-01   2025-08-05              amit@    Average  4000.000000
4   2025-08-05   2025-08-05  priya@example.com  Excellent  5985.000000
5   2025-08-01   2025-08-05     karan#mail.com       Poor  1314.285714
6   2025-08-07   2025-08-12       not provided        Bad  1995.000000
7   2025-08-01   2025-08-05   neha@example.com  No Review  3000.000000
8   2025-08-09   2025-08-13             vikas@       Good  5247.142857
9   2025-08-10   2025-08-14   asha@example.com  Excellent  4400.000000

   DeliveryTime  ReviewScore
0             4            4
1             4            2
2             5            0
3             4            3
4             0            5
5             4            1
6             5            2
7             4            0
8             4            4
9             4            5

### Optional- Round off

In [28]:
# Convert specific columns to integer
cols_to_int = ["Age", "Price", "Quantity", "Discount", "TotalPrice", "DeliveryTime", "ReviewScore"]

for col in cols_to_int:
    df[col] = df[col].round(0).astype(int)

# Display DataFrame
df

,CustomerID,CustomerName,Age,Price,Quantity,Discount,ReceivedDate,DeliveryDate,Email,Review,TotalPrice,DeliveryTime,ReviewScore
0,101,Raj,25,500,2,5,2025-08-01,2025-08-05,raj@example.com,Good,995,4,4
1,102,Unknown,34,1500,2,10,2025-08-01,2025-08-05,not provided,Bad,3740,4,2
2,103,Simran,30,1314,3,0,2025-08-01,2025-08-06,simran@example,No Review,3943,5,0
3,104,Amit,34,2000,2,0,2025-08-01,2025-08-05,amit@,Average,4000,4,3
4,105,Priya,45,1200,5,15,2025-08-05,2025-08-05,priya@example.com,Excellent,5985,0,5
5,106,Karan,29,1314,1,0,2025-08-01,2025-08-05,karan#mail.com,Poor,1314,4,1
6,107,Neha,34,800,2,5,2025-08-07,2025-08-12,not provided,Bad,1995,5,2
7,108,Unknown,33,1000,3,0,2025-08-01,2025-08-05,neha@example.com,No Review,3000,4,0
8,109,Vikas,34,1314,4,10,2025-08-09,2025-08-13,vikas@,Good,5247,4,4
9,110,Asha,40,2200,2,0,2025-08-10,2025-08-14,asha@example.com,Excellent,4400,4,5